### PR TITLE
Updated APNs for Trinidad and Tobago

### PR DESCRIPTION
**Pull request by LeetPirate**
Updated APNs for Trinidad and Tobago

### CODE REVIEW

**Comment by neobuddy89** [comment]
lol.

**Comment by TheComputerGuy96** [comment]
@LeetPirate LineageOS uses Gerrit to push changes

**Comment by TheComputerGuy96** [comment]
Hi there;

This is an automated reply, to let you know LineageOS doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at https://zifnab.net/~zifnab/wiki_dump/Howto:_Gerrit.html

Thanks!

**Comment by lineageos-gerrit** [comment]
Hi there;

This is an automated reply, to let you know LineageOS doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Pull request closed without merging**
