### PR TITLE
Sensitive numbers for Belgium

### PR DESCRIPTION
**Pull request by sonicvince**
Source:
http://www.sos112.be/fr/autres-numeros-d-urgence.html
http://www.sos112.be/nl/andere-noodnummers.html
http://www.sos112.be/de/andere-notrufnummern.html
http://www.sos112.be/en/other-emergency-numbers.html

Not the same numbers on all pages because of different spoken languages.

### CODE REVIEW

**Comment by lineageos-gerrit** [comment]
Hi there;
This is an automated reply, to let you know LineageOS doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Comment by Notch8864** [comment]
Would you like me to apply the patches you want submitted?

**Comment by sonicvince** [comment]
Hi Matt,

Well if to submit the change I have to take a whole dev environment from
Git and do a commit (as the links I received in other e-mails seem to
imply), then yes please.

If on the other hand there's a simpler way to submit it to Gerrit, then
please let me know, I'll be glad to do it myself. That way I could also
update it later if I find more sensitive numbers, the information is quite
scattered unfortunately.

Thanks!

**Comment by haveneersrobin** [comment]
I'll add them via an inline edit via Gerrit (https://review.lineageos.org/#/c/179135/)

**Comment by sonicvince** [comment]
Great, thanks.

**Comment by Notch8864** [comment]
Hey, so it's been a while, and I think my PC crashed, so it never got pushed unless someone else did it.

**Comment by sonicvince** [comment]
OK...Is there some *detailed* explanation on how to submit that to Gerrit?
I feel it should be ridiculously simple, yet I can't find a good
explanation on how that works.

**Comment by zifnab06** [comment]
https://wiki.lineageos.org/usinggerrit-howto.html

FWIW - its practically the same as git. you can clone using the URL here (https://review.lineageos.org/#/admin/projects/LineageOS/android_vendor_cm), and instead of doing "git push origin branchname", do "git push origin HEAD:refs/for/branchname", if you don't feel like syncing the whole tree.

**Pull request closed without merging**
